In [20]:
import numpy as np

a = np.arange(6).reshape((3,2))
b = np.arange(8).reshape((2,4))
result = np.dot(a, b)

print(f'{a}\n')
print(f'{b}\n')
print(f'{result}\n')
print(result.max())

[[0 1]
 [2 3]
 [4 5]]

[[0 1 2 3]
 [4 5 6 7]]

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]

47
